### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by jfexyz** [greensheep/terraform-aws-rancher-server#1]
Terraform supports [git references](https://www.terraform.io/docs/modules/sources.html), so if you tagged any updates to this source, users wouldn't need to fork the repo to prevent updates from affecting their infrastructure. 

Example: `source = "github.com/greensheep/terraform-aws-rancher-server?ref=tagName"`

**Comment by greensheep** [comment]
No problem, I've tagged the latest master and will keep it up going forwards.
