### ISSUE TITLE
rancher-delete-host is a private bitbucket repo

### ISSUE THREAD

**Issue by theturtle32** [greensheep/terraform-aws-rancher-server#4]
The [rancher-delete-host repo on bitbucket.org](https://bitbucket.org/tom_greensheep/rancher-delete-host) is private, preventing me from vetting the code or forking it.

We don't run untrusted docker images on our infrastructure. Please consider making the repo public.

**Comment by jacobwgillespie** [comment]
In case you're curious what's in there or want to build your own image, here's a copy of the app code extracted from the image: https://github.com/jacobwgillespie/greensheep-rancher-delete-host
